# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8861534fe89c06b91d0bd1f51936e580e09c5c5741f50e2e94be2a653154d1872de2cd375772c847fb07e2314cc209818279356ad7902a843cf4005450bb596e

test:
  secret_key_base: 35eec1d10daffa2515c86b885fef87d7d868bf79c9a197bc1f78ad2c4a29ed9568a15b51c837f855b2b8752601c209078a1b544be3b2cfff90d8d5d644ecd912

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
